import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@/contexts/UserContext";
import { ProfileProvider } from "@/contexts/ProfileContext";
import { PortfolioProvider } from "@/contexts/PortfolioContext";
import { TransactionsProvider } from "@/contexts/TransactionsContext";
import { ProjectsProvider } from "@/contexts/ProjectsContext";
import { UpdatesProvider } from "@/contexts/UpdatesContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserProvider>
          <ProfileProvider>
            <PortfolioProvider>
              <TransactionsProvider>
                <ProjectsProvider>
                  <UpdatesProvider>
                    {children}
                  </UpdatesProvider>
                </ProjectsProvider>
              </TransactionsProvider>
            </PortfolioProvider>
          </ProfileProvider>
        </UserProvider>
      </body>
    </html>
  );
}
